- name: Install | Install openvpn packages
  package:
    name: '{{ openvpn_gateway_distro_packages }}'
    state: '{{ openvpn_gateway_package_state }}'
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
  - install-pkgng


- name: Install | Install pf scripts
  template: src={{ item }}.sh.j2 dest=/usr/local/sbin/{{ item }}.sh mode=0755
  with_items:
  - fw_start
  - fw_stop

