---

- name: Post-Install | Create openvpn configuration directory
  file: path={{ openvpn_gateway_openvpn_dir }} state=directory

- name: Post-Install | Configure openvpn service
  template: src={{ item.source }} dest={{ item.destination }}
  with_items:
  - source: openvpn.j2
    destination: /etc/rc.conf.d/openvpn
  notify:
  - restart openvpn service

- name: Post-Install | Configure packet filter
  template: src={{ item.source }} dest={{ item.destination }}
  with_items:
  - source: pf.j2
    destination: /etc/rc.conf.d/pf
  - source: pf.rules.j2
    destination: /etc/pf.rules
  notify:
  - restart pf service

- name: Post-Install | Configure openvpn credentials
  with_items: "{{ openvpn_gateway_connections }}"
  template:
    src: login.auth.j2
    dest: "{{ openvpn_gateway_openvpn_dir }}/{{ item.name }}.login.auth"
    mode: 0600
    owner: root
    group: wheel
  notify:
  - restart openvpn service

- name: Post-Install | Configure openvpn connections
  with_items: "{{ openvpn_gateway_connections }}"
  template:
    src: openvpn.conf.j2
    dest: "{{ openvpn_gateway_openvpn_dir }}/{{ item.name }}.conf"
    owner: root
    group: wheel
  notify:
  - restart openvpn service

- name: Post-Install | Consul service definition
  with_items: "{{ openvpn_gateway_consul }}"
  when:
    - configure_consul | lower == 'true'
  notify: reload consul
  template:
    src: service.consul.json.j2
    dest: "{{ openvpn_gateway_consul_services_path }}/{{ item.service.name }}.json"

