---

- name: Pre-Install | Check operating system compatibility
  assert:
    fail_msg: "This role must be applied to FreeBSD systems"
    that: ansible_os_family == "FreeBSD"

- name: Pre-Install | Check that there is at least one server
  assert:
    fail_msg: No server defined
    that: openvpn_gateway_connection.servers | length > 0

- name: Pre-Install | Check that credentials are defined
  assert:
    fail_msg: No server defined
    that:
    - openvpn_gateway_connection.auth is defined
    - openvpn_gateway_connection.auth.login is defined
    - openvpn_gateway_connection.auth.password is defined
    - openvpn_gateway_connection.auth.login | length > 0
    - openvpn_gateway_connection.auth.password | length > 0

- name: Pre-Install | Set default facts
  set_fact:
    configure_consul: false

- name: Pre-Install | Check certificate
  assert:
    fail_msg: The given certificate is not accurate
    that:
    - openvpn_gateway_connection.certificate is defined
    - openvpn_gateway_connection.certificate | regex_replace('\n$','') | length == 1683
